// Generated by CoffeeScript 1.6.2
(function() {
  var neo, _;

  _ = require("underscore");

  neo = require("../../baio-neo4j/neo4j");

  neo.setConfig({
    uri: process.env.NEO4J_URI
  });

  exports.parseNames = function(body, type, done) {
    return done(null, []);
  };

  exports.parseNodes = function(pediaJson) {
    return null;
  };

}).call(this);

/*
//@ sourceMappingURL=parser.map
*/
