// Generated by CoffeeScript 1.6.2
(function() {
  exports.personNameReq = "select distinct ?s, ?given_name, ?sur_name, ?name, ?label, ?foaf_name\nwhere\n{\n?s ?p ?o.\noptional { ?s foaf:givenName ?given_name }\noptional { ?s foaf:surname ?sur_name }\noptional { ?s dbpprop:name ?name }\noptional { ?s rdfs:label ?label }\noptional { ?s foaf:name ?foaf_name }\nFILTER ({0})\n}";

  exports.orgNameReq = "select distinct ?s, ?name, ?label, ?foaf_name\nwhere\n{\n?s ?p ?o.\noptional { ?s dbpprop:name ?name }\noptional { ?s rdfs:label ?label }\noptional { ?s foaf:name ?foaf_name }\noptional { ?s dbpprop:nativeName ?native_name }\nFILTER ({0})\n}";

}).call(this);

/*
//@ sourceMappingURL=queries.map
*/
