// Generated by CoffeeScript 1.6.2
(function() {
  exports.parsePeople = function(batch) {
    return batch.results.bindings.map(function(d) {
      return d.s.value;
    });
  };

}).call(this);

/*
//@ sourceMappingURL=parser.map
*/
