// Generated by CoffeeScript 1.6.2
(function() {
  exports.peopleReq = "select ?s\nwhere\n{\n?s a dbpedia-owl:Person.\n} limit {0} offset {1}";

  exports.orgsReq = "select ?s\nwhere\n{\n?s a dbpedia-owl:Organisation.\n}limit {0} offset {1}";

  exports.personNameReq = "select distinct ?s, ?given_name, ?sur_name, ?name, ?label, ?foaf_name\nwhere\n{\n?s ?p ?o.\noptional { ?s foaf:givenName ?given_name }\noptional { ?s foaf:surname ?sur_name }\noptional { ?s dbpprop:name ?name }\noptional { ?s rdfs:label ?label }\noptional { ?s foaf:name ?foaf_name }\nFILTER (?s = <{0}>)\n}";

  exports.orgNameReq = "select distinct ?s, ?name, ?label, ?foaf_name\nwhere\n{\n?s ?p ?o.\noptional { ?s dbpprop:name ?name }\noptional { ?s rdfs:label ?label }\noptional { ?s foaf:name ?foaf_name }\noptional { ?s dbpprop:nativeName ?native_name }\nFILTER (?s = <{0}>)\n}";

  exports.subjectPersonLinks = "select ?p, ?o\nwhere {\n<{0}> ?p ?o.\n?o a dbpedia-owl:Person.\n}";

  exports.subjectOrgLinks = "select ?p, ?o\nwhere {\n<{0}> ?p ?o.\n?p rdfs:range ?r.\n?r rdfs:subClassOf dbpedia-owl:Organisation.\n}";

}).call(this);

/*
//@ sourceMappingURL=queries.map
*/
