// Generated by CoffeeScript 1.6.2
(function() {
  var createBatch, createLabels, createNode, createRelation, cypherQuery, neo;

  neo = require("./neo4j");

  neo.setConfig({
    uri: process.env.NEO4J_URI
  });

  cypherQuery = function() {
    return neo.query("start n=node(*) return n, labels(n), id(n);", null, function(err, data) {
      return console.log(err, data);
    });
  };

  createNode = function(uri) {
    return neo.createNode("wiki", {
      uri: uri
    }, {
      uri: uri
    }, "get_or_create", function(err, data) {
      return console.log(err, data);
    });
  };

  createLabels = function(id) {
    return neo.createLabels(id, ["huiki", "check"], function(err, data) {
      return console.log(err, data);
    });
  };

  createRelation = function(uri, n1, n2) {
    return neo.createRelation("wiki", "friend", {
      uri: 3
    }, 15, 16, {
      uri: 3
    }, "get_or_create", function(err, data) {
      return console.log(err, data);
    });
  };

  createBatch = function() {
    return neo.createBatch({
      index: "wiki",
      keyVal: (function(p) {
        return {
          uri: p.uri
        };
      }),
      strategy: "get_or_create"
    }, [
      {
        uri: 1
      }, {
        uri: 4
      }
    ], {
      index: "wiki",
      keyVal: (function(p) {
        return {
          uri: p.uri
        };
      }),
      strategy: "get_or_create",
      type: "friend"
    }, [
      {
        uri: 77
      }
    ], function(err, data) {
      return console.log(err, data);
    });
  };

  createBatch();

}).call(this);

/*
//@ sourceMappingURL=neo4j.test.map
*/
