// Generated by CoffeeScript 1.6.2
(function() {
  var cache, es, request, _del;

  request = require("./request");

  cache = require("./cache/redis");

  es = require("event-stream");

  _del = function() {
    return es.join(function(err, data) {
      var j;

      console.log("delete graph from cache : " + err);
      if (!err) {
        j = JSON.parse(data);
        console.log(j);
        return cache.del("graph", j.graphs);
      }
    });
  };

  exports.get = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.post = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.put = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.patch = function(req, res) {
    return request.req(req, res, "contribs", false, _del());
  };

  exports["delete"] = function(req, res) {
    return request.req(req, res, "contribs", false, _del());
  };

  exports.copy = function(req, res) {
    return request.req(req, res, "contribs");
  };

}).call(this);

/*
//@ sourceMappingURL=contribs.map
*/
