// Generated by CoffeeScript 1.6.2
(function() {
  var bulk, copy, req;

  req = require("request");

  bulk = function(uri, index, docs, done) {
    var doc, obj, res, _i, _len;

    res = "";
    for (_i = 0, _len = docs.length; _i < _len; _i++) {
      doc = docs[_i];
      obj = {
        "index": {
          "_index": index,
          "_type": doc._type,
          "_id": doc._id
        }
      };
      res += JSON.stringify(obj);
      res += "\r\n";
      obj = JSON.parse(JSON.stringify(doc));
      delete obj._id;
      delete obj._type;
      res += JSON.stringify(obj);
      res += "\r\n";
    }
    return req({
      method: "post",
      uri: "" + uri + "/" + index + "/_bulk",
      body: res
    }, function(err) {
      return done(err);
    });
  };

  copy = function(uri, fromIndex, toIndex, docsCount, map, done) {
    if (docsCount == null) {
      docsCount = 1000;
    }
    return req.get({
      uri: "" + uri + "/" + fromIndex + "/_search",
      qs: {
        size: docsCount
      }
    }, function(err, res) {
      var j;

      if (!err) {
        j = JSON.parse(res.body);
        j = j.hits.hits.map(function(m) {
          return map(m);
        });
        console.log(j);
        return bulk(uri, toIndex, j, done);
      } else {
        return done(err);
      }
    });
  };

  exports.copy = copy;

  exports.bulk = copy;

}).call(this);

/*
//@ sourceMappingURL=es.map
*/
