// Generated by CoffeeScript 1.6.2
(function() {
  var org, politic, _ES_URI;

  politic = require("./pedia-politic-rus-2-es-person-names");

  org = require("./pedia-org-rus-2-es-org-names");

  _ES_URI = process.env.ES_URI;

  /*
  politic.convert _ES_URI, (err) ->
    console.log "politic : ", err
  */


  org.convert(_ES_URI, function(err) {
    return console.log("org : ", err);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
