// Generated by CoffeeScript 1.6.2
(function() {
  var getDimonName, iter, should, _SPARQL_URI, _q_iter, _q_person_name;

  _q_iter = require("./pedia-iter");

  _q_person_name = require("./pedia-person-name");

  should = require("should");

  _SPARQL_URI = "http://dbpedia.org/sparql";

  getDimonName = function() {
    return _q_person_name(_SPARQL_URI, "http://dbpedia.org/resource/Dmitry_Medvedev", function(err, data) {
      should.not.exist(err);
      return should.exist(data);
    });
  };

  iter = function() {
    return _q_iter(function(err) {
      return should.not.exist(err);
    });
  };

  iter();

}).call(this);

/*
//@ sourceMappingURL=pedia.test.map
*/
