// Generated by CoffeeScript 1.6.2
(function() {
  exports.parsePeople = function(batch) {
    return batch.results.bindings.map(function(d) {
      return d.s.value;
    });
  };

  exports.parseLinks = function(batch, data) {
    var linked, links;

    linked = batch.results.bindings.map(function(m) {
      return {
        object: m.o.value,
        predicate: m.p.value
      };
    });
    links = linked.map(function(m) {
      return {
        subject: data.subject,
        predicate: m.predicate,
        object: m.object,
        type: data.type
      };
    });
    return console.log(links);
  };

}).call(this);

/*
//@ sourceMappingURL=parser.map
*/
