// Generated by CoffeeScript 1.6.2
(function() {
  var backup, es, _ES_URI;

  es = require("./es/es");

  _ES_URI = "http://188.244.44.9:9201";

  backup = function() {
    es.bkp(_ES_URI, "org-names", "person-names.bkp", function(err) {
      return console.log("person-names: " + err);
    });
    return es.bkp(_ES_URI, "org-names", "org-names.bkp", function(err) {
      return console.log("org-names: " + err);
    });
  };

  backup();

}).call(this);

/*
//@ sourceMappingURL=es.bkp.map
*/
