// Generated by CoffeeScript 1.6.2
(function() {
  var amqp, async, parseLevel, push2Amqp, req, request, requestAndParse, start, _opts, _parse;

  async = require("async");

  req = require("request");

  amqp = require("../baio-amqp/amqp");

  _opts = null;

  _parse = null;

  push2Amqp = function(level, urls) {
    var url, _i, _len, _results;

    if (urls && urls.length) {
      _results = [];
      for (_i = 0, _len = urls.length; _i < _len; _i++) {
        url = urls[_i];
        _results.push(amqp.pub(_opts.amqp.queue, {
          level: level,
          url: url
        }));
      }
      return _results;
    }
  };

  request = function(url, done) {
    if (!url.match(/https?:\/\//)) {
      url = "http://" + url;
    }
    return req({
      url: url,
      method: "get"
    }, done);
  };

  requestAndParse = function(level, url, done) {
    return async.waterfall([
      function(ck) {
        return request(url, ck);
      }, function(resp, body, ck) {
        return _parse(level, body, ck);
      }
    ], done);
  };

  parseLevel = function(level, url, done) {
    var _done;

    _done = function(err, links) {
      if (!err) {
        push2Amqp(level + 1, links);
      }
      return done(err, links);
    };
    if (url) {
      return requestAndParse(level, url, _done);
    } else {
      return _parse(level, null, _done);
    }
  };

  start = function(opts, parse, done) {
    _opts = opts;
    _parse = parse;
    amqp.setConfig(opts.amqp.config);
    return amqp.connect(function() {
      return amqp.sub({
        queue: opts.amqp.queue,
        onPop: function(data, ack) {
          return parseLevel(data.level, data.url, function(err) {
            if (!err) {
              return ack();
            }
          });
        }
      }, function(err) {
        done(err);
        if (!err) {
          return parseLevel(-1, null, function() {});
        }
      });
    });
  };

  exports.start = start;

}).call(this);

/*
//@ sourceMappingURL=crawler.map
*/
